<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Product extends Model
{
    use HasFactory;
    protected $fillable = [
        'title',
        'category_id',
        'image',
        'description',
        'price'
    ];

    public function Category(){
        return $this->belongsTo(Category::class);
    }
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($product){
            if ($product->image && Storage::disk('public')->exists($product->image)){
                Storage::disk('public')->delete($product->image);
//                Storage::disk('categories')->delete($category->image);
//                unlink(public_path($category->image));
            }
        });
    }

}
